apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-bottometh2
  name: bottometh2
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/bottometh2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-bottometh2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-bottometh2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - bottom
      containers:
      - image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
        imagePullPolicy: Always
        name: bottometh2
        args: 
          - --datadir=/data
          - --init-sync-no-verify
          - --grpc-gateway-port=7000
        ports:
        - containerPort: 4000
          hostPort: 4000
          name: 4000tcp4000
          protocol: TCP
        - containerPort: 7000
          hostPort: 7000
          name: 7000tcp7000
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: bottometh2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: bottometh2
        persistentVolumeClaim:
          claimName: bottometh2pvc
