apiVersion: v1
kind: PersistentVolume
metadata:
  name: nuc1eth2
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  hostPath:
    path: /persist/nuc1/eth2
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nuc1
  persistentVolumeReclaimPolicy: Retain
  storageClassId: null
  volumeMode: Filesystem
