apiVersion: v1
kind: PersistentVolume
metadata:
  name: bottometh1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 300Gi
  hostPath:
    path: /persist/bottom/eth1
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bottom
  persistentVolumeReclaimPolicy: Retain
  storageClassId: null
  volumeMode: Filesystem
