apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-bottometh1
  name: bottometh1
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/bottometh1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-bottometh1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-bottometh1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - bottom
      containers:
      - image: ethereum/client-go
        imagePullPolicy: Always
        name: bottometh1
        args: 
          - --rpc
          - --rpcvhosts
          - '*'
          - --rpccorsdomain
          - '*'
          - --rpcaddr
          - '0.0.0.0'
        ports:
        - containerPort: 30303
          hostPort: 30303
          name: 30303tcp303030
          protocol: TCP
        - containerPort: 8545
          hostPort: 8545
          name: 8545tcp8545
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /root/.ethereum
          name: bottometh1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: bottometh1
        persistentVolumeClaim:
          claimName: bottometh1pvc
