apiVersion: v1
kind: PersistentVolume
metadata:
  name: privateregistrypv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  hostPath:
    path: /persist/privateregistry
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - top
  persistentVolumeReclaimPolicy: Retain
  storageClassId: null
  volumeMode: Filesystem
